export interface Ingredient {
  name: string
  amount: string
}

export interface Recipe {
  ingredients: Ingredient[]
  steps: string[]
}

export interface Dish {
  id: string
  name: string
  image: string
  rating: number
  review: string
  recipe: Recipe
}

export interface Country {
  name: string
  emoji: string
  color: string
  dishes: Dish[]
}

export const countriesData: Country[] = [
  {
    name: "China",
    emoji: "🇨🇳",
    color: "from-red-600 to-yellow-500",
    dishes: [
      {
        id: "kung-pao-chicken",
        name: "Kung Pao Chicken",
        image: "/kung-pao-chicken-spicy-peanuts-asian.jpg",
        rating: 4.8,
        review: "Spicy, nutty, and absolutely delicious.",
        recipe: {
          ingredients: [
            { name: "Chicken breast", amount: "500g" },
            { name: "Peanuts", amount: "150g" },
            { name: "Soy sauce", amount: "3 tbsp" },
            { name: "Rice vinegar", amount: "2 tbsp" },
            { name: "Garlic", amount: "4 cloves" },
            { name: "Dried chili", amount: "5" },
            { name: "Sesame oil", amount: "1 tbsp" },
          ],
          steps: [
            "Cut chicken into cubes",
            "Stir-fry chicken until cooked",
            "Add garlic and chili",
            "Add peanuts",
            "Mix soy sauce and vinegar",
            "Pour sauce over chicken",
            "Drizzle with sesame oil and serve",
          ],
        },
      },
      {
        id: "mapo-tofu",
        name: "Mapo Tofu",
        image: "/mapo-tofu-spicy-numbing-sichuan.jpg",
        rating: 4.7,
        review: "Spicy, numbing, and absolutely addictive.",
        recipe: {
          ingredients: [
            { name: "Tofu", amount: "400g" },
            { name: "Ground pork", amount: "200g" },
            { name: "Doubanjiang", amount: "2 tbsp" },
            { name: "Sichuan peppercorns", amount: "1 tbsp" },
            { name: "Garlic", amount: "4 cloves" },
            { name: "Ginger", amount: "1 tbsp" },
            { name: "Soy sauce", amount: "2 tbsp" },
          ],
          steps: [
            "Cut tofu into cubes",
            "Brown ground pork",
            "Add doubanjiang and cook",
            "Add garlic and ginger",
            "Add tofu gently",
            "Add soy sauce and Sichuan peppercorns",
            "Simmer for 10 minutes",
          ],
        },
      },
      {
        id: "peking-duck",
        name: "Peking Duck",
        image: "/peking-duck-crispy-skin-roasted.jpg",
        rating: 4.9,
        review: "Crispy skin, tender meat, and absolutely luxurious.",
        recipe: {
          ingredients: [
            { name: "Whole duck", amount: "2kg" },
            { name: "Honey", amount: "3 tbsp" },
            { name: "Soy sauce", amount: "3 tbsp" },
            { name: "Rice vinegar", amount: "1 tbsp" },
            { name: "Ginger", amount: "2 slices" },
            { name: "Scallions", amount: "3" },
            { name: "Hoisin sauce", amount: "100ml" },
          ],
          steps: [
            "Clean and dry duck thoroughly",
            "Brush with honey mixture",
            "Hang to dry for 24 hours",
            "Roast at 200°C for 1.5 hours",
            "Brush with glaze halfway through",
            "Slice and serve with pancakes and sauce",
          ],
        },
      },
      {
        id: "fried-rice",
        name: "Fried Rice",
        image: "/fried-rice-egg-vegetables-asian.jpg",
        rating: 4.6,
        review: "Quick, versatile, and absolutely satisfying.",
        recipe: {
          ingredients: [
            { name: "Cooked rice", amount: "400g" },
            { name: "Eggs", amount: "3" },
            { name: "Peas and carrots", amount: "200g" },
            { name: "Soy sauce", amount: "2 tbsp" },
            { name: "Sesame oil", amount: "1 tbsp" },
            { name: "Garlic", amount: "2 cloves" },
            { name: "Green onions", amount: "2" },
          ],
          steps: [
            "Heat oil in wok",
            "Scramble eggs and set aside",
            "Stir-fry vegetables",
            "Add rice and break up clumps",
            "Add soy sauce and sesame oil",
            "Return eggs to wok",
            "Garnish with green onions",
          ],
        },
      },
      {
        id: "hot-pot",
        name: "Hot Pot",
        image: "/hot-pot-communal-broth-ingredients.jpg",
        rating: 4.8,
        review: "Interactive, fun, and absolutely delicious.",
        recipe: {
          ingredients: [
            { name: "Broth", amount: "2 liters" },
            { name: "Thinly sliced meat", amount: "500g" },
            { name: "Vegetables", amount: "500g" },
            { name: "Tofu", amount: "200g" },
            { name: "Noodles", amount: "200g" },
            { name: "Dipping sauce", amount: "as needed" },
          ],
          steps: [
            "Bring broth to boil in hot pot",
            "Arrange ingredients on platters",
            "Guests cook their own ingredients",
            "Dip in sauce before eating",
            "Add more ingredients as desired",
            "Enjoy the communal experience",
          ],
        },
      },
    ],
  },
  {
    name: "France",
    emoji: "🇫🇷",
    color: "from-blue-400 to-white",
    dishes: [
      {
        id: "coq-au-vin",
        name: "Coq au Vin",
        image: "/coq-au-vin.jpg",
        rating: 4.8,
        review: "Rich, tender, and deeply flavorful. Pure French elegance.",
        recipe: {
          ingredients: [
            { name: "Chicken", amount: "1.5kg" },
            { name: "Red wine", amount: "750ml" },
            { name: "Bacon", amount: "200g" },
            { name: "Mushrooms", amount: "300g" },
            { name: "Pearl onions", amount: "200g" },
            { name: "Garlic", amount: "4 cloves" },
            { name: "Thyme", amount: "2 sprigs" },
          ],
          steps: [
            "Brown chicken pieces in bacon fat",
            "Remove chicken and sauté vegetables",
            "Add wine and return chicken",
            "Add herbs and simmer for 1.5 hours",
            "Remove chicken and reduce sauce",
            "Return chicken to pan",
            "Serve with crusty bread",
          ],
        },
      },
      {
        id: "beef-bourguignon",
        name: "Beef Bourguignon",
        image: "/beef-bourguignon.jpg",
        rating: 4.9,
        review: "Slow-cooked perfection. A masterpiece of French cuisine.",
        recipe: {
          ingredients: [
            { name: "Beef chuck", amount: "1.5kg" },
            { name: "Red wine", amount: "750ml" },
            { name: "Beef broth", amount: "500ml" },
            { name: "Pearl onions", amount: "300g" },
            { name: "Mushrooms", amount: "300g" },
            { name: "Carrots", amount: "4" },
            { name: "Tomato paste", amount: "2 tbsp" },
          ],
          steps: [
            "Brown beef in batches",
            "Sauté vegetables",
            "Add wine and broth",
            "Add tomato paste and herbs",
            "Simmer for 3 hours until tender",
            "Skim fat from surface",
            "Serve with egg noodles",
          ],
        },
      },
      {
        id: "french-onion-soup",
        name: "French Onion Soup",
        image: "/french-onion-soup.jpg",
        rating: 4.7,
        review: "Caramelized, cheesy, and absolutely comforting.",
        recipe: {
          ingredients: [
            { name: "Onions", amount: "1kg" },
            { name: "Beef broth", amount: "1.5 liters" },
            { name: "White wine", amount: "200ml" },
            { name: "Baguette", amount: "1" },
            { name: "Gruyère cheese", amount: "200g" },
            { name: "Butter", amount: "50g" },
            { name: "Thyme", amount: "2 sprigs" },
          ],
          steps: [
            "Slice onions thinly",
            "Caramelize in butter for 45 minutes",
            "Add wine and broth",
            "Simmer for 20 minutes",
            "Toast baguette slices",
            "Top with cheese and broil",
            "Serve in bowls with bread on top",
          ],
        },
      },
      {
        id: "duck-confit",
        name: "Duck Confit",
        image: "/duck-confit.jpg",
        rating: 4.8,
        review: "Tender, succulent, and absolutely luxurious.",
        recipe: {
          ingredients: [
            { name: "Duck legs", amount: "4" },
            { name: "Duck fat", amount: "1kg" },
            { name: "Salt", amount: "2 tbsp" },
            { name: "Thyme", amount: "4 sprigs" },
            { name: "Garlic", amount: "6 cloves" },
            { name: "Bay leaves", amount: "2" },
            { name: "Black pepper", amount: "1 tsp" },
          ],
          steps: [
            "Salt duck legs and refrigerate overnight",
            "Rinse and pat dry",
            "Heat duck fat to 80°C",
            "Submerge duck legs in fat",
            "Cook for 8 hours at low temperature",
            "Cool and store in fat",
            "Reheat and crisp skin before serving",
          ],
        },
      },
      {
        id: "crème-brûlée",
        name: "Crème Brûlée",
        image: "/creme-brulee.jpg",
        rating: 4.9,
        review: "Silky, creamy, and with a perfect caramelized crust.",
        recipe: {
          ingredients: [
            { name: "Heavy cream", amount: "500ml" },
            { name: "Egg yolks", amount: "5" },
            { name: "Sugar", amount: "100g" },
            { name: "Vanilla bean", amount: "1" },
            { name: "Salt", amount: "pinch" },
          ],
          steps: [
            "Heat cream with vanilla bean",
            "Whisk egg yolks with sugar",
            "Temper eggs by slowly adding cream",
            "Strain through fine sieve",
            "Pour into ramekins",
            "Bake in water bath at 160°C for 20 minutes",
            "Chill for 4 hours, then torch sugar on top",
          ],
        },
      },
    ],
  },
  {
    name: "India",
    emoji: "🇮🇳",
    color: "from-orange-400 to-orange-600",
    dishes: [
      {
        id: "butter-chicken",
        name: "Butter Chicken",
        image: "/butter-chicken-creamy-tomato-sauce.jpg",
        rating: 4.8,
        review: "Creamy, aromatic, and absolutely delicious. A perfect blend of spices.",
        recipe: {
          ingredients: [
            { name: "Chicken breast", amount: "800g" },
            { name: "Butter", amount: "100g" },
            { name: "Heavy cream", amount: "200ml" },
            { name: "Tomato puree", amount: "150g" },
            { name: "Ginger-garlic paste", amount: "2 tbsp" },
            { name: "Garam masala", amount: "1 tsp" },
            { name: "Chili powder", amount: "1 tsp" },
          ],
          steps: [
            "Marinate chicken in yogurt and spices for 30 minutes",
            "Grill or pan-fry the chicken until cooked",
            "In a separate pan, sauté ginger-garlic paste in butter",
            "Add tomato puree and cook for 5 minutes",
            "Add cream and garam masala, simmer for 10 minutes",
            "Add cooked chicken and simmer for 5 more minutes",
            "Serve hot with rice or naan",
          ],
        },
      },
      {
        id: "biryani",
        name: "Biryani",
        image: "/biryani-rice-meat-fragrant-spiced.jpg",
        rating: 4.9,
        review: "Fragrant, layered, and bursting with flavors. A true masterpiece.",
        recipe: {
          ingredients: [
            { name: "Basmati rice", amount: "500g" },
            { name: "Lamb or chicken", amount: "800g" },
            { name: "Yogurt", amount: "200ml" },
            { name: "Onions", amount: "4 large" },
            { name: "Ginger-garlic paste", amount: "3 tbsp" },
            { name: "Biryani masala", amount: "2 tsp" },
            { name: "Saffron", amount: "1 pinch" },
          ],
          steps: [
            "Soak rice in water for 30 minutes",
            "Marinate meat in yogurt and spices for 1 hour",
            "Fry onions until golden brown",
            "Layer rice and marinated meat in a pot",
            "Add saffron soaked in milk",
            "Cover and cook on high heat for 2 minutes, then low heat for 45 minutes",
            "Let it rest for 5 minutes before serving",
          ],
        },
      },
      {
        id: "samosa",
        name: "Samosa",
        image: "/samosa-fried-triangular-pastry-potato.jpg",
        rating: 4.7,
        review: "Crispy, golden, and filled with spiced potatoes. Perfect snack!",
        recipe: {
          ingredients: [
            { name: "All-purpose flour", amount: "2 cups" },
            { name: "Potatoes", amount: "500g" },
            { name: "Peas", amount: "1 cup" },
            { name: "Onion", amount: "1 medium" },
            { name: "Green chili", amount: "2" },
            { name: "Cumin seeds", amount: "1 tsp" },
            { name: "Oil for frying", amount: "as needed" },
          ],
          steps: [
            "Make dough with flour, salt, and oil",
            "Boil and mash potatoes, mix with peas and spices",
            "Roll dough thin and cut into strips",
            "Fill with potato mixture and fold into triangles",
            "Deep fry until golden brown",
            "Serve hot with chutney",
          ],
        },
      },
      {
        id: "tandoori-chicken",
        name: "Tandoori Chicken",
        image: "/tandoori-chicken-grilled-spiced-red.jpg",
        rating: 4.8,
        review: "Smoky, tender, and perfectly spiced. A grilling masterpiece.",
        recipe: {
          ingredients: [
            { name: "Chicken pieces", amount: "1kg" },
            { name: "Yogurt", amount: "300ml" },
            { name: "Tandoori masala", amount: "3 tbsp" },
            { name: "Lemon juice", amount: "3 tbsp" },
            { name: "Ginger-garlic paste", amount: "2 tbsp" },
            { name: "Oil", amount: "2 tbsp" },
            { name: "Salt", amount: "to taste" },
          ],
          steps: [
            "Mix yogurt with tandoori masala and ginger-garlic paste",
            "Marinate chicken for at least 4 hours",
            "Preheat tandoor or grill to high heat",
            "Grill chicken until cooked through and charred",
            "Baste with oil and lemon juice while grilling",
            "Serve hot with mint chutney and lemon wedges",
          ],
        },
      },
      {
        id: "dosa",
        name: "Dosa",
        image: "/dosa-crispy-crepe-rice-lentil-batter.jpg",
        rating: 4.6,
        review: "Crispy on the outside, soft inside. A South Indian classic.",
        recipe: {
          ingredients: [
            { name: "Rice", amount: "2 cups" },
            { name: "Urad dal", amount: "1 cup" },
            { name: "Fenugreek seeds", amount: "1 tsp" },
            { name: "Salt", amount: "to taste" },
            { name: "Oil", amount: "for cooking" },
            { name: "Potato filling", amount: "as needed" },
          ],
          steps: [
            "Soak rice and urad dal separately for 4 hours",
            "Grind together to make smooth batter",
            "Ferment for 8 hours",
            "Heat griddle and spread batter thin",
            "Cook until golden and crispy",
            "Serve with sambar and chutney",
          ],
        },
      },
    ],
  },
  {
    name: "Italy",
    emoji: "🇮🇹",
    color: "from-green-400 to-red-500",
    dishes: [
      {
        id: "pasta-carbonara",
        name: "Pasta Carbonara",
        image: "/pasta-carbonara-creamy-bacon-egg.jpg",
        rating: 4.9,
        review: "Silky, rich, and perfectly balanced. Pure Italian comfort.",
        recipe: {
          ingredients: [
            { name: "Spaghetti", amount: "400g" },
            { name: "Guanciale", amount: "200g" },
            { name: "Eggs", amount: "4" },
            { name: "Pecorino Romano", amount: "100g" },
            { name: "Black pepper", amount: "1 tsp" },
            { name: "Salt", amount: "to taste" },
          ],
          steps: [
            "Cook spaghetti in salted boiling water",
            "Cut guanciale into small pieces and fry until crispy",
            "Beat eggs with grated cheese and black pepper",
            "Drain pasta, reserving 1 cup pasta water",
            "Mix hot pasta with guanciale and fat",
            "Remove from heat and add egg mixture, tossing quickly",
            "Add pasta water as needed for creaminess",
          ],
        },
      },
      {
        id: "risotto",
        name: "Risotto",
        image: "/risotto-creamy-rice-saffron-italian.jpg",
        rating: 4.8,
        review: "Creamy, luxurious, and absolutely divine.",
        recipe: {
          ingredients: [
            { name: "Arborio rice", amount: "300g" },
            { name: "White wine", amount: "150ml" },
            { name: "Vegetable broth", amount: "1 liter" },
            { name: "Onion", amount: "1 medium" },
            { name: "Butter", amount: "50g" },
            { name: "Parmesan", amount: "100g" },
            { name: "Saffron", amount: "1 pinch" },
          ],
          steps: [
            "Heat broth in a separate pot",
            "Sauté onion in butter until soft",
            "Add rice and toast for 2 minutes",
            "Add wine and stir until absorbed",
            "Add broth one ladle at a time, stirring constantly",
            "Continue for 18-20 minutes until rice is creamy",
            "Finish with butter and Parmesan",
          ],
        },
      },
      {
        id: "margherita-pizza",
        name: "Margherita Pizza",
        image: "/margherita-pizza-tomato-mozzarella-basil.jpg",
        rating: 4.7,
        review: "Simple, fresh, and absolutely perfect. Classic Italian.",
        recipe: {
          ingredients: [
            { name: "Pizza dough", amount: "500g" },
            { name: "Tomato sauce", amount: "200ml" },
            { name: "Fresh mozzarella", amount: "250g" },
            { name: "Fresh basil", amount: "10 leaves" },
            { name: "Olive oil", amount: "3 tbsp" },
            { name: "Salt", amount: "to taste" },
          ],
          steps: [
            "Preheat oven to 250°C",
            "Stretch dough into pizza shape",
            "Spread tomato sauce evenly",
            "Tear mozzarella and distribute",
            "Drizzle with olive oil",
            "Bake for 12-15 minutes until crust is golden",
            "Top with fresh basil before serving",
          ],
        },
      },
      {
        id: "lasagna",
        name: "Lasagna",
        image: "/lasagna-layered-pasta-meat-sauce-cheese.jpg",
        rating: 4.8,
        review: "Layers of comfort and flavor. A true Italian classic.",
        recipe: {
          ingredients: [
            { name: "Lasagna sheets", amount: "12" },
            { name: "Ground beef", amount: "500g" },
            { name: "Tomato sauce", amount: "400ml" },
            { name: "Béchamel sauce", amount: "500ml" },
            { name: "Mozzarella", amount: "300g" },
            { name: "Parmesan", amount: "100g" },
            { name: "Onion", amount: "1" },
          ],
          steps: [
            "Brown ground beef with onion",
            "Add tomato sauce and simmer for 20 minutes",
            "Layer pasta, meat sauce, and béchamel",
            "Top with mozzarella and Parmesan",
            "Bake at 180°C for 40 minutes until golden",
            "Let rest for 10 minutes before serving",
          ],
        },
      },
      {
        id: "tiramisu",
        name: "Tiramisu",
        image: "/tiramisu-dessert-mascarpone-coffee-cocoa.jpg",
        rating: 4.9,
        review: "Heavenly, creamy, and coffee-infused. Pure bliss.",
        recipe: {
          ingredients: [
            { name: "Mascarpone", amount: "500g" },
            { name: "Eggs", amount: "4" },
            { name: "Sugar", amount: "100g" },
            { name: "Ladyfinger biscuits", amount: "24" },
            { name: "Strong coffee", amount: "300ml" },
            { name: "Cocoa powder", amount: "2 tbsp" },
            { name: "Marsala wine", amount: "50ml" },
          ],
          steps: [
            "Whisk egg yolks with sugar until pale",
            "Fold in mascarpone gently",
            "Dip ladyfingers in coffee and arrange in dish",
            "Spread half the mascarpone mixture",
            "Repeat layers",
            "Dust with cocoa powder",
            "Refrigerate for 4 hours before serving",
          ],
        },
      },
    ],
  },
  {
    name: "Japan",
    emoji: "🇯🇵",
    color: "from-red-400 to-red-600",
    dishes: [
      {
        id: "sushi",
        name: "Sushi",
        image: "/sushi.jpg",
        rating: 4.9,
        review: "Fresh, delicate, and perfectly balanced. An art form.",
        recipe: {
          ingredients: [
            { name: "Sushi rice", amount: "300g" },
            { name: "Nori sheets", amount: "4" },
            { name: "Fresh salmon", amount: "200g" },
            { name: "Cucumber", amount: "1" },
            { name: "Avocado", amount: "1" },
            { name: "Rice vinegar", amount: "3 tbsp" },
            { name: "Wasabi", amount: "1 tbsp" },
          ],
          steps: [
            "Cook sushi rice and season with vinegar",
            "Place nori on bamboo mat",
            "Spread thin layer of rice",
            "Add fillings in a line",
            "Roll tightly using the mat",
            "Slice with a wet knife",
            "Serve with soy sauce and wasabi",
          ],
        },
      },
      {
        id: "ramen",
        name: "Ramen",
        image: "/ramen.jpg",
        rating: 4.8,
        review: "Comforting, flavorful, and deeply satisfying.",
        recipe: {
          ingredients: [
            { name: "Ramen noodles", amount: "400g" },
            { name: "Chicken broth", amount: "1.5 liters" },
            { name: "Pork belly", amount: "300g" },
            { name: "Eggs", amount: "4" },
            { name: "Green onions", amount: "2" },
            { name: "Soy sauce", amount: "3 tbsp" },
            { name: "Mirin", amount: "2 tbsp" },
          ],
          steps: [
            "Simmer pork belly until tender",
            "Prepare broth with soy sauce and mirin",
            "Boil eggs for 6-7 minutes for soft yolk",
            "Cook noodles according to package",
            "Heat broth and pour into bowls",
            "Add noodles and toppings",
            "Serve immediately while hot",
          ],
        },
      },
      {
        id: "tempura",
        name: "Tempura",
        image: "/tempura.jpg",
        rating: 4.7,
        review: "Light, crispy, and absolutely delightful.",
        recipe: {
          ingredients: [
            { name: "All-purpose flour", amount: "1 cup" },
            { name: "Egg", amount: "1" },
            { name: "Ice water", amount: "1 cup" },
            { name: "Shrimp", amount: "300g" },
            { name: "Vegetables", amount: "500g" },
            { name: "Oil for frying", amount: "as needed" },
            { name: "Dipping sauce", amount: "as needed" },
          ],
          steps: [
            "Mix flour, egg, and ice water for batter",
            "Heat oil to 170°C",
            "Dip ingredients in batter",
            "Fry until golden and crispy",
            "Drain on paper towels",
            "Serve with dipping sauce",
          ],
        },
      },
      {
        id: "tonkatsu",
        name: "Tonkatsu",
        image: "/tonkatsu.jpg",
        rating: 4.8,
        review: "Crispy, juicy, and absolutely satisfying.",
        recipe: {
          ingredients: [
            { name: "Pork loin", amount: "400g" },
            { name: "Panko breadcrumbs", amount: "1 cup" },
            { name: "Eggs", amount: "2" },
            { name: "All-purpose flour", amount: "1 cup" },
            { name: "Oil for frying", amount: "as needed" },
            { name: "Tonkatsu sauce", amount: "100ml" },
            { name: "Cabbage", amount: "200g" },
          ],
          steps: [
            "Pound pork to even thickness",
            "Coat with flour, then egg, then panko",
            "Heat oil to 170°C",
            "Fry until golden brown on both sides",
            "Drain on paper towels",
            "Serve with sauce and shredded cabbage",
          ],
        },
      },
      {
        id: "miso-soup",
        name: "Miso Soup",
        image: "/miso-soup.jpg",
        rating: 4.6,
        review: "Simple, comforting, and deeply nourishing.",
        recipe: {
          ingredients: [
            { name: "Dashi broth", amount: "1 liter" },
            { name: "Miso paste", amount: "3 tbsp" },
            { name: "Tofu", amount: "200g" },
            { name: "Seaweed", amount: "2 sheets" },
            { name: "Green onions", amount: "2" },
            { name: "Mushrooms", amount: "100g" },
          ],
          steps: [
            "Heat dashi broth",
            "Cut tofu into cubes",
            "Add mushrooms and simmer",
            "Dissolve miso in a ladle with broth",
            "Pour miso mixture into soup",
            "Add tofu and seaweed",
            "Garnish with green onions and serve",
          ],
        },
      },
    ],
  },
  {
    name: "Mexico",
    emoji: "🇲🇽",
    color: "from-green-500 to-red-600",
    dishes: [
      {
        id: "tacos",
        name: "Tacos",
        image: "/tacos.jpg",
        rating: 4.8,
        review: "Flavorful, fresh, and endlessly customizable.",
        recipe: {
          ingredients: [
            { name: "Corn tortillas", amount: "12" },
            { name: "Beef or chicken", amount: "500g" },
            { name: "Onion", amount: "1" },
            { name: "Cilantro", amount: "1 bunch" },
            { name: "Lime", amount: "2" },
            { name: "Salsa", amount: "200ml" },
            { name: "Lettuce", amount: "1 head" },
          ],
          steps: [
            "Season and cook meat with onion",
            "Warm tortillas on griddle",
            "Fill with meat and toppings",
            "Add cilantro and squeeze lime",
            "Serve with salsa",
          ],
        },
      },
      {
        id: "chiles-rellenos",
        name: "Chiles Rellenos",
        image: "/chiles-rellenos.jpg",
        rating: 4.7,
        review: "Roasted, stuffed, and smothered in sauce. Delicious.",
        recipe: {
          ingredients: [
            { name: "Poblano peppers", amount: "6" },
            { name: "Oaxaca cheese", amount: "300g" },
            { name: "Eggs", amount: "4" },
            { name: "Tomato sauce", amount: "400ml" },
            { name: "Onion", amount: "1" },
            { name: "Garlic", amount: "3 cloves" },
            { name: "Oil", amount: "2 tbsp" },
          ],
          steps: [
            "Roast peppers until charred",
            "Peel off skin carefully",
            "Make a slit and remove seeds",
            "Stuff with cheese",
            "Beat eggs and dip peppers",
            "Fry until golden",
            "Serve with tomato sauce",
          ],
        },
      },
      {
        id: "guacamole",
        name: "Guacamole",
        image: "/guacamole.jpg",
        rating: 4.9,
        review: "Creamy, fresh, and absolutely irresistible.",
        recipe: {
          ingredients: [
            { name: "Avocados", amount: "3" },
            { name: "Lime", amount: "1" },
            { name: "Cilantro", amount: "1/4 bunch" },
            { name: "Onion", amount: "1/4" },
            { name: "Tomato", amount: "1" },
            { name: "Jalapeño", amount: "1" },
            { name: "Salt", amount: "to taste" },
          ],
          steps: [
            "Cut avocados in half and remove pit",
            "Scoop into a bowl",
            "Mash to desired consistency",
            "Add lime juice immediately",
            "Fold in remaining ingredients",
            "Taste and adjust seasoning",
            "Serve immediately",
          ],
        },
      },
      {
        id: "enchiladas",
        name: "Enchiladas",
        image: "/enchiladas.jpg",
        rating: 4.8,
        review: "Rolled, sauced, and baked to perfection.",
        recipe: {
          ingredients: [
            { name: "Corn tortillas", amount: "12" },
            { name: "Chicken", amount: "500g" },
            { name: "Enchilada sauce", amount: "500ml" },
            { name: "Cheese", amount: "300g" },
            { name: "Onion", amount: "1" },
            { name: "Sour cream", amount: "200ml" },
            { name: "Cilantro", amount: "1/4 bunch" },
          ],
          steps: [
            "Shred cooked chicken",
            "Mix with cheese and onion",
            "Dip tortillas in sauce",
            "Fill and roll tightly",
            "Place seam-side down in baking dish",
            "Pour remaining sauce over top",
            "Bake at 180°C for 25 minutes",
          ],
        },
      },
      {
        id: "ceviche",
        name: "Ceviche",
        image: "/ceviche.jpg",
        rating: 4.7,
        review: "Fresh, zesty, and incredibly refreshing.",
        recipe: {
          ingredients: [
            { name: "Fresh white fish", amount: "500g" },
            { name: "Lime juice", amount: "200ml" },
            { name: "Red onion", amount: "1" },
            { name: "Cilantro", amount: "1/2 bunch" },
            { name: "Tomato", amount: "2" },
            { name: "Jalapeño", amount: "1" },
            { name: "Salt", amount: "to taste" },
          ],
          steps: [
            "Cut fish into small cubes",
            "Cover with lime juice",
            "Refrigerate for 30 minutes",
            "Add onion, cilantro, tomato, and jalapeño",
            "Mix gently",
            "Taste and adjust seasoning",
            "Serve chilled",
          ],
        },
      },
    ],
  },
]

export const DISHES_BY_COUNTRY = countriesData.reduce(
  (acc, country) => {
    acc[country.name] = country.dishes
    return acc
  },
  {} as Record<string, Dish[]>,
)
